### ISSUE TITLE
Yolo optimalisatie

### ISSUE THREAD

**Issue by Mellow420** [HvA-Robotics/kobuki-vision#11]
Verbeteren van het YOLO algoritme.

**Comment by mbakker96** [comment]
getest met het draaien van in yolo3. Heeft geen snelheid verbetering, en zelfs snelheid verliest. We mochten het nog niet testen op de robot zelf van Miguel.

**Comment by b0ster** [comment]
Werkt het resizen van een image? Bijvoorbeeld 5x verkleinen

**Comment by b0ster** [comment]
Zie nieuwe readme voor de optimalisatie
